package com.itmo.console_interface;

public enum Commands {
    PRINT_INFO_CURRENT_ACCOUNT,
    ADD_DEBIT_ACCOUNT,
    ADD_CREDIT_ACCOUNT,
    ADD_DEPOSIT_ACCOUNT,
    CHOOSE_ACCOUNT,
    DELETE_ACCOUNT_BY_ID,
    DISSIPATE_DAYS,
    DISSIPATE_MONTHS,
    ADD_FUNDS,
    WITHDRAW_FUNDS,
    TRANSFER_FUNDS,
    UNDO_LAST_COMMAND,
    READ_NOTIFICATIONS,
    CLEAR_NOTIFICATIONS,
    DISCARD_NOTIFICATIONS,
    SET_NEW_TRANSACTION_LIMIT_FOR_UNREGISTERED_CUSTOMER,
    SET_NEW_TRANSACTION_LIMIT_FOR_REGISTERED_CUSTOMER,
    SET_NEW_DEBIT_ANNUAL_INTEREST_ON_BALANCE,
    SET_NEW_CREDIT_LIMIT_AMOUNT,
    SET_NEW_CREDIT_FEE,
    LIST_ALL_CUSTOMERS_ACCOUNTS
}
